import Head from "next/head";
import Image from "next/image";
import ButtonGoogle from "@/styles/Button.module.css";
import { Inter } from "next/font/google";
import Button from "@mui/material/Button";
import { Typography } from "@mui/material";
import {
  useSession,
  signIn,
  getSession,
  GetSessionParams,
} from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>bird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "4fr 3fr",
            height: "100dvh",
            // border: "1px solid red",
          }}
        >
          <div
            style={{
              background:
                "linear-gradient(212.38deg, rgba(85, 110, 230, 0.7) 0%, rgba(147, 165, 255, 0.71) 100%),url(https://static.seattletimes.com/wp-content/uploads/2019/01/web-typing-ergonomics-1020x680.jpg)",
              backgroundRepeat: "no-repeat",
              backgroundSize: "cover",
              //"linear-gradient(212.38deg, rgba(85, 110, 230, 0.7) 0%, rgba(147, 165, 255, 0.71) 100%),url(https://static.seattletimes.com/wp-content/uploads/2019/01/web-typing-ergonomics-1020x680.jpg)",
            }}
          />

          <div
            style={{
              // border: "1px solid green",
              display: "flex",
              flexDirection: "column",
              padding: "34px",
            }}
          >
            <div
              style={{
                backgroundColor: "blue",
                borderRadius: "50%",
                width: "48px",
                aspectRatio: "1 / 1",
                marginTop: "48px",
                marginBottom: "48px",
              }}
            ></div>
            <Typography variant="h2" fontWeight={"bold"} py={3}>
              Happening now
            </Typography>
            <Typography variant="h4" fontWeight={"bold"} py={3}>
              Join [Twitter] today.
            </Typography>
            <div
              style={{
                maxWidth: "300px",
                display: "flex",
                flexDirection: "column",
              }}
            >
              <button className={ButtonGoogle.googleBtn}>
                Sign in with Google
              </button>
              <button
                className={ButtonGoogle.gitHubbtn}
                style={{ marginTop: "24px" }}
                onClick={() => {
                  signIn();
                }}
              >
                Sign in with GitHub
              </button>
              <Typography fontWeight={"bold"} textAlign={"center"} py={2}>
                or
              </Typography>
              <Button
                variant="contained"
                sx={{ borderRadius: "20px" }}
                onClick={() => {
                  signIn();
                }}
              >
                Create account
              </Button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetSessionParams) {
  const session = await getSession(context);

  if (session !== null) {
    return {
      redirect: {
        permanent: false,
        destination: "/home",
      },
    };
  } else {
    return {
      props: {},
    };
  }
}
